/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `party` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `party`;

CREATE TABLE IF NOT EXISTS `phaser` (
  `ID` varchar(50) DEFAULT NULL,
  `HP` int DEFAULT NULL,
  `STAGE` int DEFAULT NULL,
  `COIN` int DEFAULT NULL,
  `DAMAGE` int DEFAULT NULL,
  `SPEED` int DEFAULT NULL,
  `STAGEMODE` varchar(50) DEFAULT NULL,
  `PETENABLE` varchar(50) DEFAULT NULL,
  `WATERGAUGEMAX` int DEFAULT NULL,
  `UPDATETIME` varchar(50) DEFAULT NULL,
  `SCORE` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `pt_accompanyboard_attend` (
  `ATTEND_SEQ` int NOT NULL AUTO_INCREMENT COMMENT '고유번호',
  `BOARD_ID` int NOT NULL DEFAULT '0' COMMENT '참가원 ID',
  `ID` varchar(20) NOT NULL,
  `ATTEND_DATE` varchar(20) NOT NULL DEFAULT '',
  `ATTEND_STATE` tinyint NOT NULL DEFAULT '1' COMMENT '참석 여부',
  PRIMARY KEY (`ATTEND_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='모임글 참가 테이블';

CREATE TABLE IF NOT EXISTS `pt_accompanyboard_post` (
  `NO` int NOT NULL AUTO_INCREMENT COMMENT '게시판 번호',
  `WRITER` varchar(64) NOT NULL COMMENT '작성자 ID',
  `REG_DATE` varchar(20) NOT NULL COMMENT '게시글 등록 일자',
  `MODIFY_DATE` varchar(20) DEFAULT NULL COMMENT '게시글 수정 일자',
  `IS_DELETE` tinyint DEFAULT '0' COMMENT '게시글 삭제 여부',
  `WRITER_COUNTRY` varchar(20) NOT NULL DEFAULT 'KOREA' COMMENT '작성자 국적',
  `COUNTRY_CODE` varchar(20) NOT NULL COMMENT '여행 나라코드',
  `AREA_CODE` varchar(20) NOT NULL COMMENT '여행 지역코드',
  `CATEGORY` varchar(20) NOT NULL COMMENT '카테고리',
  `MEET_DATE` varchar(10) NOT NULL COMMENT '모임 일자',
  `MEET_TIME` varchar(10) DEFAULT NULL COMMENT '모임 시간',
  `HEADCOUNT_NOW` tinyint DEFAULT '1',
  `HEADCOUNT` tinyint NOT NULL COMMENT '모임 인원',
  `PLACE` varchar(300) DEFAULT NULL COMMENT '모임 장소',
  `SOURCE` varchar(600) DEFAULT NULL COMMENT '출처',
  `CONTACT` varchar(128) NOT NULL COMMENT '연락처',
  `TITLE` varchar(64) NOT NULL COMMENT '제목',
  `CONTENTS` varchar(5000) NOT NULL COMMENT '내용',
  `HASHTAG` varchar(128) DEFAULT NULL COMMENT '해쉬태그',
  `LIMIT_AGE_MIN` tinyint DEFAULT '20' COMMENT '나이제한',
  `LIMIT_AGE_MAX` tinyint DEFAULT '80',
  `LIMIT_GENDER` varchar(10) DEFAULT 'nothing' COMMENT '성별제한',
  `AUTOPARTION` tinyint(1) NOT NULL DEFAULT '0' COMMENT '자동참가여부',
  `LATITUDE` varchar(50) DEFAULT NULL,
  `LONGITUDE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`NO`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='모임 게시판 관련 글';

CREATE TABLE IF NOT EXISTS `pt_accompanyboard_reply` (
  `REPLY_ID` int NOT NULL AUTO_INCREMENT COMMENT '댓글 번호',
  `BOARD_ID` int NOT NULL COMMENT '게시판 ID',
  `DEPTH` tinyint DEFAULT NULL COMMENT '답글의 깊이',
  `BUNDLE_ID` int DEFAULT NULL COMMENT '댓글과 대댓글을 하나로 묶을 ID',
  `BUNDLE_ORDER` tinyint DEFAULT NULL COMMENT '답글의 깊이,위치',
  `USER_ID` varchar(50) NOT NULL COMMENT '댓글 작성자 ID',
  `REPLY` varchar(50) NOT NULL COMMENT '댓글 내용',
  `REG_DATE` varchar(20) NOT NULL COMMENT '댓글 등록 일자',
  PRIMARY KEY (`REPLY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='모임 게시판 댓글 관련 테이블';

CREATE TABLE IF NOT EXISTS `pt_area` (
  `SEQ` int NOT NULL AUTO_INCREMENT COMMENT '번호',
  `CONTINENT` varchar(50) NOT NULL DEFAULT '' COMMENT '대륙',
  `COUNTRY` varchar(50) NOT NULL DEFAULT '' COMMENT '나라',
  `AREA` varchar(50) NOT NULL DEFAULT '' COMMENT '지역',
  `AREA_CODE` varchar(10) NOT NULL DEFAULT '' COMMENT '지역 코드',
  `IMG` varchar(200) DEFAULT '' COMMENT '이미지',
  `COUNTRY_CODE` varchar(50) NOT NULL COMMENT '나라코드',
  `REST_AREA_CODE` varchar(10) DEFAULT NULL,
  `REST_SIGUNGU_CODE` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='지원가능 지역';

CREATE TABLE IF NOT EXISTS `pt_category` (
  `SEQ` tinyint NOT NULL DEFAULT '0' COMMENT '번호',
  `CATEGORY` varchar(50) NOT NULL DEFAULT '0' COMMENT '카테고리',
  `IMG` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0' COMMENT '카테고리 이미지',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='여행 카테고리';

CREATE TABLE IF NOT EXISTS `pt_phaser` (
  `ID` varchar(64) NOT NULL,
  `NO` int NOT NULL AUTO_INCREMENT,
  `MAP_DATA` varchar(10000) NOT NULL DEFAULT '0',
  `REG_DATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0',
  `MODIFY_DATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `MAP_ID` varchar(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`NO`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `pt_phaser_tower` (
  `ID` varchar(64) NOT NULL,
  `NO` int NOT NULL AUTO_INCREMENT,
  `MAP_DATA` varchar(10000) NOT NULL DEFAULT '0',
  `REG_DATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0',
  `MODIFY_DATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `MAP_ID` varchar(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`NO`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `pt_phaser_tower_count` (
  `NO` int NOT NULL AUTO_INCREMENT,
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MAP_ID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `COUNT` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `REG_DATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `MODIFY_DATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`NO`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `pt_style` (
  `SEQ` int NOT NULL AUTO_INCREMENT,
  `STYLE` varchar(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='호칭 타이틀';

CREATE TABLE IF NOT EXISTS `pt_style_user` (
  `NO` int NOT NULL AUTO_INCREMENT COMMENT '자동증가',
  `ID` varchar(50) NOT NULL DEFAULT '0' COMMENT '유저ID',
  `ID_GET_SEQ` int NOT NULL DEFAULT '0' COMMENT '유저가 획득한 칭호 SEQ',
  `IS_MAIN_STYLE` tinyint(1) NOT NULL DEFAULT '0' COMMENT '이름앞에 들어갈 칭호',
  `IS_SUB_STYLE` tinyint(1) NOT NULL DEFAULT '0' COMMENT '6개 제한 서브 칭호',
  PRIMARY KEY (`NO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='유저의 칭호 저장';

CREATE TABLE IF NOT EXISTS `pt_tourlist_category` (
  `SEQ` int NOT NULL AUTO_INCREMENT,
  `CATEGORY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `IMG` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CODE` varchar(10) NOT NULL,
  PRIMARY KEY (`SEQ`),
  UNIQUE KEY `CATEGORY` (`CATEGORY`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `pt_user` (
  `SEQ` int NOT NULL AUTO_INCREMENT COMMENT '번호',
  `ID` varchar(20) NOT NULL DEFAULT '0' COMMENT '유저 아이디',
  `PASSWORD` varchar(200) NOT NULL DEFAULT '0' COMMENT '비밀번호',
  `NAME` varchar(30) NOT NULL DEFAULT '0' COMMENT '이름',
  `IMG` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'https://ssl.pstatic.net/static/pwe/address/img_profile.png' COMMENT '프로필 이미지',
  `GENDER` varchar(10) DEFAULT NULL COMMENT '성별',
  `BIRTHDAY` varchar(20) DEFAULT NULL COMMENT '나이',
  `NATION` varchar(20) DEFAULT NULL COMMENT '국적',
  `ISBLOCK` tinyint(1) DEFAULT '0' COMMENT '계정 잠금 여부',
  `SALT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MODFY_DATE` varchar(20) DEFAULT NULL,
  `REG_DATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IS_CREATE` tinyint DEFAULT '0',
  `IS_BLOCKED` tinyint DEFAULT '0',
  `IS_DELETE` tinyint DEFAULT '0',
  `ISADMIN` tinyint DEFAULT '0',
  `PASSWORD_NOT_CORRECT` int DEFAULT '0',
  PRIMARY KEY (`SEQ`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='유저테이블 정보';

CREATE TABLE IF NOT EXISTS `pt_user_info` (
  `NO` int NOT NULL AUTO_INCREMENT,
  `REG_DATE` varchar(20) NOT NULL,
  `MODIFY_DATE` varchar(20) NOT NULL,
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GOLD` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `pt_user_tour` (
  `SEQ` int NOT NULL AUTO_INCREMENT COMMENT '일정 번호',
  `WRITER` varchar(20) NOT NULL COMMENT '작성자',
  `AREA_CODE` varchar(10) NOT NULL COMMENT '지역 코드',
  `START_DATE` varchar(20) NOT NULL COMMENT '시작 날짜',
  `END_DATE` varchar(20) NOT NULL COMMENT '종료 날짜',
  `REG_DATE` varchar(20) NOT NULL COMMENT '등록 일자',
  `MODIFY_DATE` varchar(20) DEFAULT NULL COMMENT '수정 일자',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='내 여행 일정';

CREATE TABLE IF NOT EXISTS `sessions` (
  `session_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `expires` int unsigned NOT NULL,
  `data` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  PRIMARY KEY (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `test_photo` (
  `SEQ` int NOT NULL AUTO_INCREMENT,
  `ID` varchar(20) NOT NULL DEFAULT '0',
  `IMG` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0',
  `LATX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `LONGY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `REG_DATE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `tour_scrap` (
  `SEQ` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) DEFAULT NULL,
  `ID` varchar(50) DEFAULT NULL,
  `CONTENT_ID` varchar(50) DEFAULT NULL,
  `IMG` varchar(256) DEFAULT NULL,
  `START_DATE` varchar(50) DEFAULT NULL,
  `END_DATE` varchar(50) DEFAULT NULL,
  `TITLE` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
